//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.netProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        private int v1;
        private object cityId;
        private string v2;
        private object cityName;

        public City()
        {
        }

        public City(int cityId, string cityName)
        {
            CityId = cityId;
            CityName = cityName;
        }

        public City(int v1, object cityId, string v2, object cityName)
        {
            this.v1 = v1;
            this.cityId = cityId;
            this.v2 = v2;
            this.cityName = cityName;
        }

        public int CityId { get; set; }
        public string CityName { get; set; }
    }
}
