//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.netProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplaintType()
        {
            this.ComplaintResolutions = new HashSet<ComplaintResolution>();
        }
    
        public int ComplaintTypeId { get; set; }
        public string ComplaintType1 { get; set; }
        public Nullable<int> ComplaintCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintResolution> ComplaintResolutions { get; set; }
    }
}
