//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.netProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintResolution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComplaintResolution()
        {
            this.CustomerComplaints = new HashSet<CustomerComplaint>();
            this.CustomerComplaints1 = new HashSet<CustomerComplaint>();
        }
    
        public int ResolutionId { get; set; }
        public string ResolutionDescription { get; set; }
        public int ResolutionAmount { get; set; }
        public Nullable<int> ComplaintType { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> Monthformation { get; set; }
    
        public virtual AgentInformation AgentInformation { get; set; }
        public virtual ComplaintType ComplaintType1 { get; set; }
        public virtual month month { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerComplaint> CustomerComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerComplaint> CustomerComplaints1 { get; set; }
    }
}
