//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.netProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerComplaint
    {
        public int ComplaintId { get; set; }
        public string ComplaintDescription { get; set; }
        public System.DateTime ComplaintDate { get; set; }
        public System.DateTime ComplaintResolvedDate { get; set; }
        public Nullable<int> ComplaintType { get; set; }
        public Nullable<int> ComplintStatus { get; set; }
        public Nullable<int> ResolvedBy { get; set; }
        public Nullable<int> ResolveInformation { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual AgentInformation AgentInformation { get; set; }
        public virtual ComplaintResolution ComplaintResolution { get; set; }
        public virtual ComplaintResolution ComplaintResolution1 { get; set; }
        public virtual ComplaintStatu ComplaintStatu { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
