//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.netProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentHistory
    {
        public int PaymentId { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> PaymentStatusId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> AccountStatusId { get; set; }
        public Nullable<System.DateTime> PaymentDuedate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Status Status { get; set; }
        public virtual paymentStetu paymentStetu { get; set; }
    }
}
