//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.netProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class month
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public month()
        {
            this.ComplaintResolutions = new HashSet<ComplaintResolution>();
            this.NewPackagePrices = new HashSet<NewPackagePrice>();
        }
    
        public int monthId { get; set; }
        public Nullable<System.DateTime> monthDate { get; set; }
        public string monthName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintResolution> ComplaintResolutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewPackagePrice> NewPackagePrices { get; set; }
    }
}
