//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.netProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPackagePrice
    {
        public int PackageId { get; set; }
        public int NewPackagePrice1 { get; set; }
        public Nullable<int> MonthId { get; set; }
        public Nullable<int> OLDPACKAGEID { get; set; }
        public Nullable<int> YEAR { get; set; }
    
        public virtual month month { get; set; }
        public virtual Package Package { get; set; }
    }
}
