//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado.netProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package_Log_Table
    {
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public Nullable<int> PackagePrice { get; set; }
        public Nullable<int> ChannelId { get; set; }
    }
}
